version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak-oidc-server
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin123
    ports:
      - "8081:8080" # Use port 8081 to avoid conflict with Tomcat (8080)
    command: start-dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
`